connection_string: "DefaultEndpointsProtocol=https;AccountName=techradar0;AccountKey=0gANNxqY86OT6Elq8IT0Pw/mH6Pfvm4tTeClhJx6pk1HwkzeteUSTkVdHUoL/rROgSLhj+tqWAFfBKpSfMbOZw==;EndpointSuffix=core.windows.net"
container_name: "container0"
key: "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"
topic_file: "Tags_Search_Terms.tsv"
